import os
import shutil
import glob
import sys
import site
import psycopg2

def fix_psycopg2_dlls():
    """Copy PostgreSQL DLLs and psycopg2 module to the dist directory"""
    # Create necessary directories
    dist_dir = 'dist'
    psycopg2_dir = os.path.join(dist_dir, 'psycopg2')
    os.makedirs(psycopg2_dir, exist_ok=True)
    
    # Get source psycopg2 directory
    src_psycopg2_dir = os.path.dirname(psycopg2.__file__)
    print(f"Source psycopg2 directory: {src_psycopg2_dir}")
    
    # Copy entire psycopg2 directory
    for item in os.listdir(src_psycopg2_dir):
        src_item = os.path.join(src_psycopg2_dir, item)
        dst_item = os.path.join(psycopg2_dir, item)
        
        if os.path.isfile(src_item):
            shutil.copy2(src_item, dst_item)
            print(f"Copied {src_item} to {dst_item}")
    
    # PostgreSQL installation directories
    pg_dirs = [
        r'C:\Program Files\PostgreSQL\17\bin',
        r'C:\Program Files\PostgreSQL\16\bin',
        r'C:\Program Files\PostgreSQL\15\bin',
        r'C:\Program Files\PostgreSQL\14\bin',
    ]
    
    # Required DLLs for PostgreSQL 17
    dlls = [
        'libpq.dll',
        'libssl-3.dll', 'libssl-1_1-x64.dll', 'libssl-1_1.dll',
        'libcrypto-3.dll', 'libcrypto-1_1-x64.dll', 'libcrypto-1_1.dll',
        'libintl-9.dll', 'libintl-8.dll',
        'libiconv-2.dll',
        'zlib1.dll',
        'libwinpthread-1.dll'
    ]
    
    # Copy DLLs to multiple locations for maximum compatibility
    for dll in dlls:
        found = False
        for pg_dir in pg_dirs:
            dll_path = os.path.join(pg_dir, dll)
            if os.path.exists(dll_path):
                # Copy to root directory
                shutil.copy2(dll_path, dist_dir)
                print(f"Copied {dll_path} to {dist_dir}")
                
                # Copy to psycopg2 directory
                shutil.copy2(dll_path, psycopg2_dir)
                print(f"Copied {dll_path} to {psycopg2_dir}")
                
                found = True
                break
        
        if not found:
            print(f"WARNING: Could not find {dll}")
    
    # Create a simple __init__.py to ensure the directory is recognized as a package
    with open(os.path.join(psycopg2_dir, '__init__.py'), 'w') as f:
        f.write('# Generated by fix_psycopg2.py\n')
        f.write('from . import _psycopg\n')
    
    print("\nFix completed. If the application still fails, try running it with:")
    print("set PATH=%PATH%;C:\\Program Files\\PostgreSQL\\17\\bin")

if __name__ == "__main__":
    fix_psycopg2_dlls()